version: 2.1

orbs:
  kube: circleci/kubernetes@1.3.0

jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.0.0
      - image: circleci/mongo:4.0.28-xenial-ram
    steps:
      - checkout
      - run:
          command: bundle install && bundle exec rspec
  rubocop:
    docker:
      - image: cimg/ruby:3.0.0
    steps:
      - checkout
      - run:
          command: bundle install && bundle exec rubocop
  deploy:
    docker:
      - image: buildpack-deps:18.04
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - kube/install-kubectl
      - kube/install-kubeconfig
      - run:
          name: Fix the version for the docker and kubernetes executions
          command: export VERSION=$(date +%s)
      - run:
          name: Build the image to be able to push it online
          command: docker build -t virtuatable/auth-api:${VERSION} -f deployment/Dockerfile .
      - run:
          name: Push the image to the DockerHub DTR
          command: docker push virtuatable/auth-api:${VERSION}
      - run:
          name: Deploys the application on Kubernetes
          command: sed s/[VERSION]/${VERSION}/g deployment/infrastructure.yml kubectl apply -f -

workflows:
  build:
    jobs:
      - rspec
      - rubocop
      - deploy