version: 2.1

jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.0.0
      - image: circleci/mongodb:4.0.28-xenial-ram
    steps:
      - checkout
      - run:
          name: "Run tests in the repository"
          command: "bundle exec rspec"

workflows:
  build:
    jobs:
      - rspec
