development:
  clients:
    default:
      database: virtuatable
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: virtuatable-tests
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false